# Fail2ban upstream package on Debian Bookworm does not ship samba.conf.
# This filter targets Samba auth failures emitted into /var/log/ad/log.smbd.

[Definition]
failregex = ^\s*Auth: \[[^]]+\] user \[[^]]+\] at \[[^]]+\] with \[[^]]+\] status \[NT_STATUS_(?:WRONG_PASSWORD|NO_SUCH_USER|LOGON_FAILURE)\].*remote host \[ipv4:<HOST>:[0-9]+\].*$
            ^\s*\{"timestamp": ".*", "type": "Authentication", "Authentication": \{.*"status": "NT_STATUS_(?:WRONG_PASSWORD|NO_SUCH_USER|LOGON_FAILURE)".*"remoteAddress": "ipv4:<HOST>:[0-9]+".*\}\}\s*$

ignoreregex =
