# Adapted from upstream fail2ban slapd filter to support OpenLDAP RESULT lines
# that include qtime/etime fields after err=49.

[INCLUDES]
before = common.conf

[Definition]
_daemon = slapd
failregex = ^.*conn=(?P<_conn_>\d+) fd=\d+ ACCEPT from IP=<HOST>:\d+ \(IP=\S+\)\s*<SKIPLINES>^.*conn=(?P=_conn_) op=\d+ RESULT.* err=49 .*$
ignoreregex =

[Init]
maxlines = 20
