listen = *
protocols = imap

disable_plaintext_auth = no
auth_mechanisms = plain login

mail_home = /var/mail/%n
mail_location = maildir:~/Maildir

passdb {
  driver = passwd-file
  args = /run/hacktrap/dovecot.passwd
}

userdb {
  driver = passwd-file
  args = username_format=%n /run/hacktrap/dovecot.passwd
}

service imap-login {
  inet_listener imap {
    port = 143
  }
}

ssl = no

log_path = /var/log/imap/dovecot.log
info_log_path = /var/log/imap/dovecot.log
auth_verbose = yes
