[global]
workgroup = HACKTRAP
server string = HackTrap Active Directory honeypot
server role = standalone server
security = user
passdb backend = tdbsam
map to guest = Never
restrict anonymous = 2
lanman auth = no
ntlm auth = ntlmv2-only
logging = file
log file = /var/log/ad/log.smbd
max log size = 0
log level = 2 auth:5
load printers = no
printing = bsd
disable spoolss = yes
server min protocol = SMB2
smb ports = 445
bind interfaces only = yes
interfaces = lo eth0

[share]
path = /srv/ad/share
browseable = yes
read only = no
guest ok = no
