if ($syslogfacility-text == "auth" or $syslogfacility-text == "authpriv") then {
  action(
    type="omfile"
    file="/var/log/telnet/auth.log"
    template="RSYSLOG_TraditionalFileFormat"
  )
  stop
}
