[Definition]
failregex = ^.*snmptrapd\[\d+\]: Authentication failed.*from UDP: \[<HOST>\](?::\d+)?(?:->\[[^]]+\]:\d+)?\s*$
            ^.*snmptrapd\[\d+\]: .*community.*from UDP: \[<HOST>\](?::\d+)?(?:->\[[^]]+\]:\d+)?\s*$
            ^.*snmptrapd\[\d+\]: .*No access.*from UDP: \[<HOST>\](?::\d+)?(?:->\[[^]]+\]:\d+)?\s*$
