listen=YES
listen_ipv6=NO
anonymous_enable=NO
local_enable=YES
write_enable=NO
dirmessage_enable=NO
use_localtime=YES
xferlog_enable=YES
connect_from_port_20=YES
secure_chroot_dir=/run/vsftpd/empty
pam_service_name=vsftpd
utf8_filesystem=YES
background=NO
dual_log_enable=YES
log_ftp_protocol=YES
vsftpd_log_file=/var/log/ftp/vsftpd.log
