[global]
   workgroup = WORKGROUP
   server string = HackTrap SMB honeypot
   server role = standalone server
   security = user
   map to guest = never
   restrict anonymous = 2
   smb ports = 445
   disable netbios = yes
   log level = 2 auth:3
   logging = file
   log file = /var/log/smb/log.smbd
   max log size = 10000
   load printers = no
   printing = bsd
   printcap name = /dev/null
   unix password sync = yes
   passdb backend = tdbsam
   obey pam restrictions = yes

[trapshare]
   comment = HackTrap SMB Share
   path = /srv/smb/trapshare
   browseable = yes
   writable = yes
   guest ok = no
   read only = no
   valid users = @smbusers,root
   force group = smbusers
   create mask = 0660
   directory mask = 0770
