[Definition]
failregex = ^.*(?:Authentication failed|AUTHENTICATION_FAILED).*\(from (?:\[::ffff:\])?<HOST>:\d+\).*$
            ^.*(?:Authentication failed|AUTHENTICATION_FAILED).*(?:for user [^ ]+ from|from) (?:\[::ffff:\])?<HOST>(?::\d+)?.*$
