[Definition]
failregex = ^\s*Auth:\s+\[[^\]]+\]\s+user\s+\[[^\]]+\].*status\s+\[NT_STATUS_(?:WRONG_PASSWORD|NO_SUCH_USER|LOGON_FAILURE|ACCOUNT_LOCKED_OUT)\].*remote host\s+\[ipv[46]:<HOST>:[0-9]+\].*$

ignoreregex =
