driftfile /var/lib/ntpsec/ntp.drift

# Restrict anonymous control/management operations.
restrict default kod nomodify nopeer noquery limited
restrict -6 default kod nomodify nopeer noquery limited
restrict 127.0.0.1
restrict ::1
